version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - env
      - mvn test
      - hogeaaaaaa
  post_build:
    commands:
      - echo Build completed on `date`
      - env
      - mvn package
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar
